name: Checkout Repository
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: ls -a
            - name: Checkout repository
              run: |
                  git init
                  git remote add origin "https://${{secrets.GITHUB_TOKEN}}@github.com/$github_repository.git"
                  git fetch origin
                  git checkout main
            - name: List files after
              run: ls -a
