name: Working Dirs & Shells
on: [push]
defaults:
    run:
        shell: bash
jobs:
    working-dir-and-shells-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Display current working directory and list files
              run: |
                  pwd
                  ls -a
                  echo $GITHUB_SHA
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_WORKSPACE

    working-dir-and-shells-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display current working directory and list files
              run: |
                  Get-Location
                  dir
                  echo $env:GITHUB_SHA
                  echo $env:GITHUB_REPOSITORY
                  echo $env:GITHUB_WORKSPACE
    working-dir-and-shells-windows-bash:
        runs-on: windows-latest
        steps:
            - name: Display current working directory and list files
              run: |
                  Get-Location
                  dir
                  echo $env:GITHUB_SHA
                  echo $env:GITHUB_REPOSITORY
                  echo $env:GITHUB_WORKSPACE
